### ISSUE TITLE
Splunk Output mode >1 broken, 8.4.0

### ISSUE THREAD

**Issue by Paymh** [mosajjal/dnsmonster#1] opened 2021-07-13 05:06 UTC
Hello,

It seems the filtering/allow logic is broken for the Splunk HEC Output as once the splunkOutputType is increased above 1, all domains get skipped, no matter what is in/not in the allow/skip files:
{"level":"info","msg":"output: {Name:splunk SentToOutput:0 Skipped:99441}","time":"2021-07-13T15:03:29+10:00"}
{"level":"info","msg":"{PacketsGot:99485 PacketsLost:0 PacketLossPercent:0}","time":"2021-07-13T15:03:29+10:00"}

Config file:
useAfpacket=true
devName=myerspan
splunkOutputType=3
skipDomainsFile=/app/dnsmonster/filterDomains.csv
splunkOutputEndpoint=<redacted>:8088
splunkOutputToken=<redacted>
skipTlsVerification=true
splunkOutputIndex=<redacted>
splunkOutputSource=<redacted>
splunkOutputSourceType=<redacted>

filterDomains:
empty

Are you able to please advise if something is wrong with the config or if this bug has been fixed in commits past the 8.4.0 release?

Thanks,
Lachlan

**Comment by mosajjal** [comment] 2021-07-14 23:20
Hi Lachlan,

I see `splunkOutputEndpoint` is set to `:8088`, can you please confirm if that's the case or you've omitted the IP there.

I tested this a couple of times before pushing to 0.8.4 and it worked fine. I'll do more testing to see where the problem would be. I will also add some debug logging for skip and allow matching to make sure the logic is well-represented.

Cheers,

**Comment by Paymh** [comment] 2021-07-14 23:48
Hey Ali,

Yes meant to be redacted. Please see my referenced pull request for the fix to this issue #2.

Cheers,
Lachlan

**Comment by mosajjal** [comment] 2021-07-15 00:14
Understood. Can you confirm if you're trying to get allowdomains logic working (splunkOutputType=3) so only certain domains gets logged and everything else gets skipped. if that's the case, an empty/nil file input for allowDomainsFile means 0 output, which makes 100% skip the intended behavior.

Looking at #2, I think rather than changing the default behavior of returning `false` or `true`, we can have default returns for case 2 and case 3, since the defaults for those would be different. (in 2 it would be false and for 3 it would be true)

**Comment by Paymh** [comment] 2021-07-15 00:31
I had not explicitely tried `splunkOutputType=3`, you are right that my changes will likely have broken that, apologies. Your solution sounds reasonable to fix all scenarios :)

PS: This project has been a real life-saver for my organisation!

**Comment by mosajjal** [comment] 2021-07-15 01:25
Glad to hear it! Please keep the feedbacks coming :) I'll issue a fix for the logic shortly and will close #2 as a result. Feel free to close this if it answers all your issue

**Closed** 2021-07-18 23:17 UTC
